### ISSUE TITLE
Main Url for documentation gives 404

### ISSUE THREAD

**Issue by jeanluc33** [SubPointSolutions/subpointsolutions-docs#47]
This url gives a 404.  Making it very difficult to assess this API!

http://docs.subpointsolutions.com/spmeta2/

**Comment by SubPointSupport** [comment]
Updating, it will be 'offiline' next 12-16 hours.

As a workaround. change "http://docs.subpointsolutions.com/" to "http://subpointsolutions-prod-docs.azurewebsites.net/" for every single url. For instance:

Provision scenarios: 
http://subpointsolutions-prod-docs.azurewebsites.net/spmeta2/scenarios/

List views: 
http://subpointsolutions-prod-docs.azurewebsites.net//spmeta2/definitions/sharepoint-foundation/ListViewDefinition

**Comment by jeanluc33** [comment]
Glad to hear.  Say, are you aware of any sample resources re: deploying managed meta-data column?  I downloaded the sample Contoso project but there didn't appear to be any managed meta-data / taxonomy examples in there.

**Comment by SubPointSupport** [comment]
Regression tests can be used for the time being.

https://github.com/SubPointSolutions/spmeta2/blob/master/SPMeta2/SPMeta2.Regression.Tests/Impl/Scenarios/TaxonomyFieldScenariousTest.cs

.AddRandomTermStore() will be as AddTermStore() with the correct term store definition.
taxField goes as an instance of TaxonomyFieldDefinition - with the ID/InternalName/Group/Description, and the tax-specific props such as TermSeName/TermSetId and so on.

You can deploy "empty" tax field, without any binding skipping TermSetId/Name and the rest of the props.

You can also specific TaxGroup/TaxTermSet/TaxTerm by Name/Id, so that the field will be linked to the correct term. Either Name or ID props should be used.

**Comment by SubPointSupport** [comment]
All back.
